name = "GBIF2"
uuid = "dedd4f52-e074-43bf-924d-d6bce14ad628"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
